#!/usr/bin/env bun
/**
 * Optimized build script for GitHub Action
 *
 * This script:
 * 1. Compiles the WebAssembly module
 * 2. Applies wasm-opt optimizations
 * 3. Converts the optimized WASM binary to a base64 string
 * 4. Injects the base64 string into the wasm-inline.ts file
 * 5. Bundles everything into a single optimized file
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'fs';
import { join, resolve, dirname } from 'path';
import * as esbuild from 'esbuild';

// Configuration
const DIST_DIR = './dist';
const PKG_DIR = './pkg';
const WASM_FILE = 'action_wasm_bg.wasm';
const WASM_JS_FILE = 'action_wasm.js';
const WASM_OPT_ARGS = ['-Oz', '--enable-mutable-globals', '--strip-debug', '--strip-producers'];

// Ensure the dist directory exists
if (!existsSync(DIST_DIR)) {
  mkdirSync(DIST_DIR, { recursive: true });
}

// Step 1: Compile the WebAssembly module with optimized settings
console.log('Compiling WebAssembly module...');
try {
  // Use the rustup version of wasm-pack by setting the PATH
  const env = { ...process.env };
  env.PATH = `${process.env.HOME}/.cargo/bin:${env.PATH}`;

  execSync('cd wasm && wasm-pack build --target nodejs --out-dir ../pkg --release', {
    stdio: 'inherit',
    env
  });
  console.log('WebAssembly compilation successful');
} catch (error) {
  console.error('WebAssembly compilation failed:', error);
  process.exit(1);
}

// Step 2: Apply wasm-opt optimizations
console.log('Applying wasm-opt optimizations...');
const wasmPath = resolve(join(PKG_DIR, WASM_FILE));
const wasmOptPath = resolve(join(PKG_DIR, 'optimized_' + WASM_FILE));

try {
  // Check if wasm-opt is installed
  try {
    execSync('which wasm-opt', { stdio: 'ignore' });
  } catch (error) {
    console.warn('wasm-opt not found. Skipping additional optimizations.');
    // Copy the original file to the optimized path
    copyFileSync(wasmPath, wasmOptPath);
  }

  // Run wasm-opt if available
  try {
    const wasmOptCmd = `wasm-opt ${WASM_OPT_ARGS.join(' ')} -o "${wasmOptPath}" "${wasmPath}"`;
    execSync(wasmOptCmd, { stdio: 'inherit' });
    console.log('wasm-opt optimizations applied successfully');

    // Replace the original WASM file with the optimized one
    copyFileSync(wasmOptPath, wasmPath);
  } catch (error) {
    console.warn('wasm-opt optimization failed, using original WASM file:', error);
  }
} catch (error) {
  console.warn('Error during wasm-opt step:', error);
  // Continue with the build process even if wasm-opt fails
}

// Step 3: Convert the WASM binary to a base64 string
console.log('Converting WASM to base64...');
if (!existsSync(wasmPath)) {
  console.error(`WASM file not found at ${wasmPath}`);
  process.exit(1);
}

const wasmBuffer = readFileSync(wasmPath);
const wasmBase64 = wasmBuffer.toString('base64');
console.log(`WASM size: ${wasmBuffer.length} bytes, Base64 size: ${wasmBase64.length} bytes`);

// Step 4: Inject the base64 string into the wasm-inline.ts file
console.log('Injecting base64 into wasm-inline.ts...');
const wasmInlinePath = resolve('./src/wasm-inline.ts');
let wasmInlineContent = readFileSync(wasmInlinePath, 'utf8');
wasmInlineContent = wasmInlineContent.replace(
  /export const WASM_BASE64 = ['"]WASM_BASE64_PLACEHOLDER['"];/,
  `export const WASM_BASE64 = '${wasmBase64}';`
);
writeFileSync(wasmInlinePath, wasmInlineContent);
console.log('Base64 WASM injected successfully');

// Step 5: Bundle everything into a single optimized file
console.log('Bundling JavaScript...');
try {
  await esbuild.build({
    entryPoints: ['./src/index.ts'],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'esm',
    outfile: join(DIST_DIR, 'index.js'),
    minify: false, // Disable minification to avoid issues with function names
    treeShaking: true,
    banner: {
      js: '// GitHub Action with WebAssembly optimization (inlined)\n// This file was generated by the build-optimized.ts script\n',
    },
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    // Optimize for faster startup
    metafile: true,
    sourcemap: false,
    legalComments: 'none',
  });
  console.log('JavaScript bundling completed successfully');
} catch (error) {
  console.error('JavaScript bundling failed:', error);
  process.exit(1);
}

// Print final stats
const finalBundleSize = readFileSync(join(DIST_DIR, 'index.js')).length;
console.log(`Final bundle size: ${finalBundleSize} bytes`);
console.log('Build completed successfully!');
